version: '3.3'

services:
  db1:
    build:
      context: ./labs/1
    restart: always
    container_name: sql-lab1
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sam'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9001:3306'
    expose:
      - '9001'
      
  db2:
    build:
      context: ./labs/2
    restart: always
    container_name: sql-lab2
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sam'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9002:3306'
    expose:
      - '9002'

  db3:
    build:
      context: ./labs/3
    restart: always
    container_name: sql-lab3
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sam'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9003:3306'
    expose:
      - '9003'
  db4:
    build:
      context: ./labs/4
    restart: always
    container_name: sql-lab4
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sam'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9004:3306'
    expose:
      - '9004'

  db5:
    build:
      context: ./labs/5
    restart: always
    container_name: sql-lab5
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sam'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '9005:3306'
    expose:
      - '9005'